#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF

CREATE USER backend WITH PASSWORD '$DB_PASSWORD';

CREATE DATABASE codex ENCODING UTF8;

GRANT CONNECT ON DATABASE codex TO backend;

GRANT USAGE ON SCHEMA public TO backend;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO backend;

CREATE DATABASE okved ENCODING UTF8;

GRANT USAGE ON SCHEMA public TO backend;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO backend;

GRANT CONNECT ON DATABASE okved TO backend;

CREATE DATABASE ervk ENCODING UTF8;

GRANT USAGE ON SCHEMA public TO backend;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO backend;

GRANT CONNECT ON DATABASE ervk TO backend;

CREATE DATABASE reference ENCODING UTF8;

GRANT CONNECT ON DATABASE reference TO backend;

GRANT USAGE ON SCHEMA public TO backend;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO backend;


EOF