#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF

CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';

CREATE DATABASE codex ENCODING UTF8;

GRANT CONNECT ON DATABASE codex TO $DB_USER;

GRANT USAGE ON SCHEMA public TO $DB_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;

CREATE DATABASE okved ENCODING UTF8;

GRANT USAGE ON SCHEMA public TO $DB_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;

GRANT CONNECT ON DATABASE okved TO $DB_USER;

CREATE DATABASE ervk ENCODING UTF8;

GRANT USAGE ON SCHEMA public TO $DB_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;

GRANT CONNECT ON DATABASE ervk TO $DB_USER;

CREATE DATABASE reference ENCODING UTF8;

GRANT CONNECT ON DATABASE reference TO $DB_USER;

GRANT USAGE ON SCHEMA public TO $DB_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;


EOF